#USE THE OFFICAL UBUNTU IMAGE AS THE BASE IMAGE
FROM ubuntu
#UPDATE THE PACKAGE AND INSTALL APACHE2
RUN apt-get update -y && \
    apt-get install apache2 -y
#COPY THE INDEX.HTML FILE TO THE APACHE SERVER ROOT DIRECTORY
COPY index.html /var/www/html/
#START THE APACHE SERVER IN THE FOREGROUND
CMD ["usr/sbin/apachectl", "-D", "FOREGROUND"]

